export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const REORDER_INGREDIENTS = 'REORDER_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
